---
# Playbook for creating a user and configuring SSH in Debian Distributions
- name: Crear multiples usuarios con SSH
  hosts: all
  become: yes

  vars:
    users:
      - name: ansible
        ssh_key: "~/.ssh/id_rsa.pub"
      - name: devops
        ssh_key: "~/.ssh/devops.pub"

    disable_password_auth: true
    allow_passwordless_sudo: true

  tasks:
    - name: Crear usuarios
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: yes
      loop: "{{ users }}"

    - name: Agregar claves SSH
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', item.ssh_key) }}"
      loop: "{{ users }}"

    - name: Agregar usuarios al grupo sudo
      user:
        name: "{{ item.name }}"
        groups: sudo
        append: yes
      loop: "{{ users }}"

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted